import block_concrete_2 from '@/assets/images/maps/block_concrete_2.jpg';
import block_bricks_1 from '@/assets/images/maps/block_bricks_2.png';
import headquarters from '@/assets/images/maps/headquarters.png';
import placeStart from '@/assets/images/maps/place_start.png';
import block_bricks_1_hit_1 from '@/assets/images/maps/block_bricks_2_hit_1.png';
import del_block_bricks_2 from '@/assets/images/maps/del_block_bricks_2.png';
import type { MapGame, PlacesStart } from '@/types/map';

export const placesStartMap_1: PlacesStart = [
   {
      coord: [900, 0],
      countHit: 0,
      link: placeStart,
      part: 'map',
      nameId: 'placeStart',
      type: 'placeStart',
   },
   {
      coord: [400, 50],
      countHit: 0,
      link: placeStart,
      part: 'map',
      type: 'placeStart',
      nameId: 'placeStart',
   },
   {
      part: 'map',
      link: placeStart,
      countHit: 0,
      type: 'placeStart',
      coord: [50, 150],
      nameId: 'placeStart',
   },
   {
      part: 'map',
      link: placeStart,
      countHit: 0,
      type: 'placeStart',
      coord: [850, 150],
      nameId: 'placeStart',
   },
   {
      coord: [550, 750],
      countHit: 0,
      link: placeStart,
      part: 'map',
      type: 'placeMyStart',
      nameId: 'placeStart',
   },
];

export const map_1: MapGame = {
   '0': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 0],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [200, 0],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 0],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [600, 0],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 0],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [700, 0],
      },
   ],
   '50': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 50],
      },
   ],
   '100': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [0, 100],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [50, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [100, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [400, 100],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [450, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [500, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [800, 100],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [850, 100],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [900, 100],
      },
   ],
   '150': [
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [0, 150],
      },

      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [200, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [700, 150],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 150],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [900, 150],
      },
   ],
   '200': [
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [200, 200],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 200],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 200],
      },

      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 200],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [700, 200],
      },
   ],
   '250': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [400, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [500, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 250],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 250],
      },
   ],
   '300': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [300, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [600, 300],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 300],
      },
   ],
   '350': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [100, 350],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 350],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 350],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [800, 350],
      },
   ],
   '400': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [0, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [50, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [100, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [200, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [300, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [400, 400],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [450, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [500, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [600, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [700, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [800, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [850, 400],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [900, 400],
      },
   ],
   '450': [
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [350, 450],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [450, 450],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [550, 450],
      },
   ],
   '500': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [200, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [250, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [300, 500],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [350, 500],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [550, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [600, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [650, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [700, 500],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 500],
      },
   ],
   '550': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 550],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 550],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 550],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 550],
      },
   ],
   '600': [
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [50, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [100, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [150, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [300, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [350, 600],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [400, 600],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [450, 600],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [500, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [550, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [600, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [750, 600],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [800, 600],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [850, 600],
      },
   ],
   '650': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [50, 650],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [100, 650],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [800, 650],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [850, 650],
      },
   ],
   '700': [
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [0, 700],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [50, 700],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [300, 700],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [400, 700],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [450, 700],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [500, 700],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [600, 700],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [850, 700],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [900, 700],
      },
   ],
   '750': [
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [0, 750],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [50, 750],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [300, 750],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [400, 750],
      },
      {
         part: 'map',
         link: headquarters,
         countHit: 0,
         nameId: 'headquarters',
         type: 'headquarters',
         coord: [450, 750],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [500, 750],
      },
      {
         part: 'map',
         nameId: 'block_concrete_2',
         link: block_concrete_2,
         countHit: 0,
         type: 'concrete',
         coord: [600, 750],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [850, 750],
      },
      {
         part: 'map',
         nameId: 'block_bricks_1',
         link: block_bricks_1,
         linkHit1: block_bricks_1_hit_1,
         linkDel: del_block_bricks_2,
         countHit: 0,
         type: 'bricks',
         coord: [900, 750],
      },
   ],
};
