import block_concrete_2 from '@/assets/images/maps/block_concrete_2.jpg';
import block_bricks_1 from '@/assets/images/maps/block_bricks_2.png';
import headquarters from '@/assets/images/maps/headquarters.png';
import placeStart from '@/assets/images/maps/place_start.png';
import block_bricks_1_hit_1 from '@/assets/images/maps/block_bricks_2_hit_1.png';
import del_block_bricks_2 from '@/assets/images/maps/del_block_bricks_2.png';
import type { MapGame, PlacesStart } from '@/types/map';

export const placesStartMap_1: PlacesStart = [
   {
      id: 1,
      coord: [900, 0],
      coordMob: [396, 0],
      countHit: 0,
      link: placeStart,
      node: 'map',
      nameId: 'placeStart',
      type: 'placeStart',
   },
   {
      id: 2,
      coord: [400, 50],
      coordMob: [176, 22],
      countHit: 0,
      link: placeStart,
      node: 'map',
      type: 'placeStart',
      nameId: 'placeStart',
   },
   {
      id: 3,
      node: 'map',
      link: placeStart,
      countHit: 0,
      type: 'placeStart',
      coord: [50, 150],
      coordMob: [22, 0],
      nameId: 'placeStart',
   },
   {
      id: 4,
      node: 'map',
      link: placeStart,
      countHit: 0,
      type: 'placeStart',
      coord: [850, 150],
      coordMob: [374, 66],
      nameId: 'placeStart',
   },
   {
      id: 5,
      coord: [550, 750],
      coordMob: [242, 330],
      countHit: 0,
      link: placeStart,
      node: 'map',
      type: 'placeMyStart',
      nameId: 'placeStart',
   },
];

export const map_1: MapGame = [
   {
      id: 6,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 0],
      coordMob: [66, 0],
   },
   {
      id: 7,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [200, 0],
      coordMob: [88, 0],
   },
   {
      id: 8,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 0],
      coordMob: [110, 0],
   },
   {
      id: 9,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [600, 0],
      coordMob: [264, 0],
   },
   {
      id: 10,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 0],
      coordMob: [286, 0],
   },
   {
      id: 11,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [700, 0],
      coordMob: [308, 0],
   },
   {
      id: 12,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 50],
      coordMob: [198, 22],
   },
   {
      id: 13,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [0, 100],
      coordMob: [0, 44],
   },
   {
      id: 14,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [50, 100],
      coordMob: [22, 44],
   },
   {
      id: 15,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [100, 100],
      coordMob: [44, 44],
   },
   {
      id: 16,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 100],
      coordMob: [66, 44],
   },
   {
      id: 17,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 100],
      coordMob: [154, 44],
   },
   {
      id: 18,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [400, 100],
      coordMob: [176, 44],
   },
   {
      id: 19,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [450, 100],
      coordMob: [198, 44],
   },
   {
      id: 20,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [500, 100],
      coordMob: [220, 44],
   },
   {
      id: 21,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 100],
      coordMob: [242, 44],
   },
   {
      id: 22,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 100],
      coordMob: [330, 44],
   },
   {
      id: 23,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [800, 100],
      coordMob: [352, 44],
   },
   {
      id: 24,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [850, 100],
      coordMob: [374, 44],
   },
   {
      id: 25,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [900, 100],
      coordMob: [396, 44],
   },
   {
      id: 26,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [0, 150],
      coordMob: [0, 66],
   },

   {
      id: 27,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 150],
      coordMob: [66, 66],
   },
   {
      id: 28,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [200, 150],
      coordMob: [88, 66],
   },
   {
      id: 29,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 150],
      coordMob: [110, 66],
   },
   {
      id: 30,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 150],
      coordMob: [198, 66],
   },
   {
      id: 31,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 150],
      coordMob: [286, 66],
   },
   {
      id: 32,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [700, 150],
      coordMob: [308, 66],
   },
   {
      id: 33,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 150],
      coordMob: [330, 66],
   },
   {
      id: 34,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [900, 150],
      coordMob: [396, 66],
   },
   {
      id: 35,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [200, 200],
      coordMob: [88, 88],
   },
   {
      id: 36,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 200],
      coordMob: [110, 88],
   },
   {
      id: 37,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 200],
      coordMob: [198, 88],
   },

   {
      id: 38,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 200],
      coordMob: [286, 88],
   },
   {
      id: 39,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [700, 200],
      coordMob: [308, 88],
   },
   {
      id: 40,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 250],
      coordMob: [110, 110],
   },
   {
      id: 41,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 250],
      coordMob: [154, 110],
   },
   {
      id: 42,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [400, 250],
      coordMob: [176, 110],
   },
   {
      id: 43,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 250],
      coordMob: [198, 110],
   },
   {
      id: 44,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [500, 250],
      coordMob: [220, 110],
   },
   {
      id: 45,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 250],
      coordMob: [242, 110],
   },
   {
      id: 46,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 250],
      coordMob: [286, 110],
   },
   {
      id: 47,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 300],
      coordMob: [110, 132],
   },
   {
      id: 48,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [300, 300],
      coordMob: [132, 132],
   },
   {
      id: 49,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 300],
      coordMob: [154, 132],
   },
   {
      id: 50,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 300],
      coordMob: [198, 132],
   },
   {
      id: 51,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 300],
      coordMob: [242, 132],
   },
   {
      id: 52,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [600, 300],
      coordMob: [264, 132],
   },
   {
      id: 53,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 300],
      coordMob: [286, 132],
   },
   {
      id: 54,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [100, 350],
      coordMob: [44, 154],
   },
   {
      id: 55,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 350],
      coordMob: [66, 154],
   },
   {
      id: 56,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 350],
      coordMob: [330, 154],
   },
   {
      id: 57,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [800, 350],
      coordMob: [352, 154],
   },
   {
      id: 58,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [0, 400],
      coordMob: [0, 176],
   },
   {
      id: 59,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [50, 400],
      coordMob: [22, 176],
   },
   {
      id: 60,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [100, 400],
      coordMob: [44, 176],
   },
   {
      id: 61,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 400],
      coordMob: [66, 176],
   },
   {
      id: 62,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [200, 400],
      coordMob: [88, 176],
   },
   {
      id: 63,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 400],
      coordMob: [110, 176],
   },
   {
      id: 64,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [300, 400],
      coordMob: [132, 176],
   },
   {
      id: 65,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 400],
      coordMob: [154, 176],
   },
   {
      id: 66,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [400, 400],
      coordMob: [176, 176],
   },
   {
      id: 67,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [450, 400],
      coordMob: [198, 176],
   },
   {
      id: 68,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [500, 400],
      coordMob: [220, 176],
   },
   {
      id: 69,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 400],
      coordMob: [242, 176],
   },
   {
      id: 70,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [600, 400],
      coordMob: [264, 176],
   },
   {
      id: 71,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 400],
      coordMob: [286, 176],
   },
   {
      id: 72,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [700, 400],
      coordMob: [308, 176],
   },
   {
      id: 73,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 400],
      coordMob: [330, 176],
   },
   {
      id: 73,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [800, 400],
      coordMob: [352, 176],
   },
   {
      id: 75,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [850, 400],
      coordMob: [374, 176],
   },
   {
      id: 76,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [900, 400],
      coordMob: [396, 176],
   },
   {
      id: 77,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [350, 450],
      coordMob: [154, 198],
   },
   {
      id: 78,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [450, 450],
      coordMob: [198, 198],
   },
   {
      id: 79,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [550, 450],
      coordMob: [242, 198],
   },
   {
      id: 80,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 500],
      coordMob: [66, 220],
   },
   {
      id: 81,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [200, 500],
      coordMob: [88, 220],
   },
   {
      id: 82,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [250, 500],
      coordMob: [110, 220],
   },
   {
      id: 83,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [300, 500],
      coordMob: [132, 220],
   },
   {
      id: 84,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [350, 500],
      coordMob: [154, 220],
   },
   {
      id: 85,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [550, 500],
      coordMob: [242, 220],
   },
   {
      id: 85,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [600, 500],
      coordMob: [264, 220],
   },
   {
      id: 87,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [650, 500],
      coordMob: [286, 220],
   },
   {
      id: 88,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [700, 500],
      coordMob: [308, 220],
   },
   {
      id: 89,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 500],
      coordMob: [330, 220],
   },
   {
      id: 90,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 550],
      coordMob: [66, 242],
   },
   {
      id: 91,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 550],
      coordMob: [154, 242],
   },
   {
      id: 92,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 550],
      coordMob: [242, 242],
   },
   {
      id: 93,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 550],
      coordMob: [330, 242],
   },
   {
      id: 94,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [50, 600],
      coordMob: [22, 264],
   },
   {
      id: 95,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [100, 600],
      coordMob: [44, 264],
   },
   {
      id: 96,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [150, 600],
      coordMob: [66, 264],
   },
   {
      id: 97,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [300, 600],
      coordMob: [132, 264],
   },
   {
      id: 98,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [350, 600],
      coordMob: [154, 264],
   },
   {
      id: 99,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [400, 600],
      coordMob: [176, 264],
   },
   {
      id: 100,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [450, 600],
      coordMob: [198, 264],
   },
   {
      id: 101,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [500, 600],
      coordMob: [220, 264],
   },
   {
      id: 102,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [550, 600],
      coordMob: [242, 264],
   },
   {
      id: 103,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [600, 600],
      coordMob: [264, 264],
   },
   {
      id: 104,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [750, 600],
      coordMob: [330, 264],
   },
   {
      id: 105,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [800, 600],
      coordMob: [352, 264],
   },
   {
      id: 106,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [850, 600],
      coordMob: [374, 264],
   },
   {
      id: 107,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [50, 650],
      coordMob: [22, 286],
   },
   {
      id: 108,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [100, 650],
      coordMob: [44, 286],
   },
   {
      id: 109,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [800, 650],
      coordMob: [352, 286],
   },
   {
      id: 110,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [850, 650],
      coordMob: [374, 286],
   },
   {
      id: 111,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [0, 700],
      coordMob: [0, 308],
   },
   {
      id: 112,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [50, 700],
      coordMob: [22, 308],
   },
   {
      id: 113,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [300, 700],
      coordMob: [132, 308],
   },
   {
      id: 114,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [400, 700],
      coordMob: [176, 308],
   },
   {
      id: 115,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [450, 700],
      coordMob: [198, 308],
   },
   {
      id: 116,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [500, 700],
      coordMob: [220, 308],
   },
   {
      id: 117,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [600, 700],
      coordMob: [264, 308],
   },
   {
      id: 118,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [850, 700],
      coordMob: [374, 308],
   },
   {
      id: 119,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [900, 700],
      coordMob: [396, 308],
   },
   {
      id: 120,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [0, 750],
      coordMob: [0, 330],
   },
   {
      id: 121,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [50, 750],
      coordMob: [22, 330],
   },
   {
      id: 122,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [300, 750],
      coordMob: [132, 330],
   },
   {
      id: 123,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [400, 750],
      coordMob: [176, 330],
   },
   {
      id: 124,
      node: 'map',
      link: headquarters,
      countHit: 0,
      nameId: 'headquarters',
      type: 'headquarters',
      coord: [450, 750],
      coordMob: [198, 330],
   },
   {
      id: 125,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [500, 750],
      coordMob: [220, 330],
   },
   {
      id: 126,
      node: 'map',
      nameId: 'block_concrete_2',
      link: block_concrete_2,
      countHit: 0,
      type: 'concrete',
      coord: [600, 750],
      coordMob: [264, 330],
   },
   {
      id: 127,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [850, 750],
      coordMob: [374, 330],
   },
   {
      id: 128,
      node: 'map',
      nameId: 'block_bricks_1',
      link: block_bricks_1,
      linkHit1: block_bricks_1_hit_1,
      linkDel: del_block_bricks_2,
      countHit: 0,
      type: 'bricks',
      coord: [900, 750],
      coordMob: [396, 330],
   },
];
// export const map_1: MapGame = {id: 1,
//    '0': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 0],
//          coordMob: [66, 0],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [200, 0],
//          coordMob: [88, 0],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 0],
//          coordMob: [110, 0],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [600, 0],
//          coordMob: [264, 0],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 0],
//          coordMob: [286, 0],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [700, 0],
//          coordMob: [308, 0],
//       },
//    ],
//    '50': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 50],
//          coordMob: [198, 22],
//       },
//    ],
//    '100': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [0, 100],
//          coordMob: [0, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [50, 100],
//          coordMob: [22, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [100, 100],
//          coordMob: [44, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 100],
//          coordMob: [66, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 100],
//          coordMob: [154, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [400, 100],
//          coordMob: [176, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [450, 100],
//          coordMob: [198, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [500, 100],
//          coordMob: [220, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 100],
//          coordMob: [242, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 100],
//          coordMob: [330, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [800, 100],
//          coordMob: [352, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [850, 100],
//          coordMob: [374, 44],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [900, 100],
//          coordMob: [396, 44],
//       },
//    ],
//    '150': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [0, 150],
//          coordMob: [0, 66],
//       },

//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 150],
//          coordMob: [66, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [200, 150],
//          coordMob: [88, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 150],
//          coordMob: [110, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 150],
//          coordMob: [198, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 150],
//          coordMob: [286, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [700, 150],
//          coordMob: [308, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 150],
//          coordMob: [330, 66],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [900, 150],
//          coordMob: [396, 66],
//       },
//    ],
//    '200': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [200, 200],
//          coordMob: [88, 88],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 200],
//          coordMob: [110, 88],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 200],
//          coordMob: [198, 88],
//       },

//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 200],
//          coordMob: [286, 88],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [700, 200],
//          coordMob: [308, 88],
//       },
//    ],
//    '250': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 250],
//          coordMob: [110, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 250],
//          coordMob: [154, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [400, 250],
//          coordMob: [176, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 250],
//          coordMob: [198, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [500, 250],
//          coordMob: [220, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 250],
//          coordMob: [242, 110],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 250],
//          coordMob: [286, 110],
//       },
//    ],
//    '300': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 300],
//          coordMob: [110, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [300, 300],
//          coordMob: [132, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 300],
//          coordMob: [154, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 300],
//          coordMob: [198, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 300],
//          coordMob: [242, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [600, 300],
//          coordMob: [264, 132],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 300],
//          coordMob: [286, 132],
//       },
//    ],
//    '350': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [100, 350],
//          coordMob: [44, 154],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 350],
//          coordMob: [66, 154],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 350],
//          coordMob: [330, 154],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [800, 350],
//          coordMob: [352, 154],
//       },
//    ],
//    '400': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [0, 400],
//          coordMob: [0, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [50, 400],
//          coordMob: [22, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [100, 400],
//          coordMob: [44, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 400],
//          coordMob: [66, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [200, 400],
//          coordMob: [88, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 400],
//          coordMob: [110, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [300, 400],
//          coordMob: [132, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 400],
//          coordMob: [154, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [400, 400],
//          coordMob: [176, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [450, 400],
//          coordMob: [198, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [500, 400],
//          coordMob: [220, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 400],
//          coordMob: [242, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [600, 400],
//          coordMob: [264, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 400],
//          coordMob: [286, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [700, 400],
//          coordMob: [308, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 400],
//          coordMob: [330, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [800, 400],
//          coordMob: [352, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [850, 400],
//          coordMob: [374, 176],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [900, 400],
//          coordMob: [396, 176],
//       },
//    ],
//    '450': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [350, 450],
//          coordMob: [154, 198],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [450, 450],
//          coordMob: [198, 198],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [550, 450],
//          coordMob: [242, 198],
//       },
//    ],
//    '500': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 500],
//          coordMob: [66, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [200, 500],
//          coordMob: [88, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [250, 500],
//          coordMob: [110, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [300, 500],
//          coordMob: [132, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [350, 500],
//          coordMob: [154, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [550, 500],
//          coordMob: [242, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [600, 500],
//          coordMob: [264, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [650, 500],
//          coordMob: [286, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [700, 500],
//          coordMob: [308, 220],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 500],
//          coordMob: [330, 220],
//       },
//    ],
//    '550': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 550],
//          coordMob: [66, 242],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 550],
//          coordMob: [154, 242],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 550],
//          coordMob: [242, 242],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 550],
//          coordMob: [330, 242],
//       },
//    ],
//    '600': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [50, 600],
//          coordMob: [22, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [100, 600],
//          coordMob: [44, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [150, 600],
//          coordMob: [66, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [300, 600],
//          coordMob: [132, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [350, 600],
//          coordMob: [154, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [400, 600],
//          coordMob: [176, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [450, 600],
//          coordMob: [198, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [500, 600],
//          coordMob: [220, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [550, 600],
//          coordMob: [242, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [600, 600],
//          coordMob: [264, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [750, 600],
//          coordMob: [330, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [800, 600],
//          coordMob: [352, 264],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [850, 600],
//          coordMob: [374, 264],
//       },
//    ],
//    '650': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [50, 650],
//          coordMob: [22, 286],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [100, 650],
//          coordMob: [44, 286],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [800, 650],
//          coordMob: [352, 286],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [850, 650],
//          coordMob: [374, 286],
//       },
//    ],
//    '700': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [0, 700],
//          coordMob: [0, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [50, 700],
//          coordMob: [22, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [300, 700],
//          coordMob: [132, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [400, 700],
//          coordMob: [176, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [450, 700],
//          coordMob: [198, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [500, 700],
//          coordMob: [220, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [600, 700],
//          coordMob: [264, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [850, 700],
//          coordMob: [374, 308],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [900, 700],
//          coordMob: [396, 308],
//       },
//    ],
//    '750': [
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [0, 750],
//          coordMob: [0, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [50, 750],
//          coordMob: [22, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [300, 750],
//          coordMob: [132, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [400, 750],
//          coordMob: [176, 330],
//       },
//       {id: 1,
//          node: 'map',
//          link: headquarters,
//          countHit: 0,
//          nameId: 'headquarters',
//          type: 'headquarters',
//          coord: [450, 750],
//          coordMob: [198, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [500, 750],
//          coordMob: [220, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_concrete_2',
//          link: block_concrete_2,
//          countHit: 0,
//          type: 'concrete',
//          coord: [600, 750],
//          coordMob: [264, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [850, 750],
//          coordMob: [374, 330],
//       },
//       {id: 1,
//          node: 'map',
//          nameId: 'block_bricks_1',
//          link: block_bricks_1,
//          linkHit1: block_bricks_1_hit_1,
//          linkDel: del_block_bricks_2,
//          countHit: 0,
//          type: 'bricks',
//          coord: [900, 750],
//          coordMob: [396, 330],
//       },
//    ],
// };
